openapi: 3.1.0
info:
  title: Event Management and User Participation API
  summary: The REST service for managing events and handling user participation.
  version: "v1.0"
servers:
  - url: https://aidsbridge-1.onrender.com
paths:
  /events:
    get:
      operationId: listEvents
      summary: List all events
      responses:
        200:
          description: An array of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
        500:
          description: Internal Server Error

    post:
      operationId: createEvent
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"
            examples:
              newEvent:
                value:
                  title: "World AIDS Day Conference"
                  description: "An event to raise awareness and support for AIDS."
                  location: "Conference Center, New York"
                  date: "2022-12-01T09:00:00Z"
      responses:
        201:
          description: Event created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
        400:
          description: Bad Request

  /events/{eventId}:
    put:
      operationId: updateEvent
      summary: Update an event's details
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
          description: The unique identifier of the event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"
            examples:
              updateEvent:
                value:
                  title: "Updated Event Title"
                  description: "Updated event description here."
                  location: "Updated Location"
                  date: "2022-12-01T09:00:00Z"
      responses:
        200:
          description: Event updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
        400:
          description: Bad Request
        404:
          description: Event not found

    delete:
      operationId: deleteEvent
      summary: Delete an event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
          description: The unique identifier of the event to be deleted
      responses:
        200:
          description: Event deleted successfully
        404:
          description: Event not found
        500:
          description: Internal Server Error

components:
  schemas:
    Event:
      type: object
      required:
        - title
        - description
        - creator
        - attendees
        - date
      properties:
        id:
          type: string
          description: Unique identifier for the event, generated by the server
          example: "e1234567-e89b-12d3-a456-426614174000"
        title:
          type: string
          description: Title of the event
          example: "World AIDS Day Conference"
        description:
          type: string
          description: Detailed description of the event
          example: "An event to raise awareness and support for AIDS."
        attendees:
          type: array
          items:
            $ref: "#/components/schemas/Attendee"
          description: List of attendees registered for the event
        date:
          type: string
          format: date-time
          description: Date and time of the event
          example: "2022-12-01T09:00:00Z"

    Attendee:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the attendee, generated by the server
          example: "123e4567-e89b-12d3-a456-426614174000"
        name:
          type: string
          description: Name of the attendee
          example: "John Doe"

    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code
          example: "BadRequest"
        message:
          type: string
          description: Error message explaining what went wrong
          example: "Invalid input data provided."
