openapi: 3.1.0
info:
  title: Resource and Consultation Services API
  summary: The REST service for managing resources, consultations, and user stories.
  version: "v1.0"
servers:
  - url: http://localhost:3000
paths:
  /find-services:
    get:
      operationId: listResources
      summary: List all resources
      responses:
        200:
          description: An array of resources
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Resource"
        500:
          description: Internal Server Error

components:
  schemas:
    Resource:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the resource
          examples: "res"
        name:
          type: string
          description: Name of the resource
          examples: "Local Support Group"
        type:
          type: string
          description: Type of the resource
          examples: "Support"
        address:
          type: string
          description: Physical address or online location of the resource
          examples: "123 Main St, Boston, MA"
        contact:
          type: string
          description: Contact information for the resource
          examples: "contact@examples.com"

    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code indicating the type of error
          examples: "ResourceNotFound"
        message:
          type: string
          description: A message describing the error
          examples: "The requested resource was not found."
